### ISSUE TITLE
show icons for favorites

### ISSUE THREAD

**Issue by PCAssistSoftware** [gep13-archive/VBForums-Enhanced-Tabbed-Web-Browser#2]
Would it be possible to improve the favorites so it shows the favorites icon/images as well i.e. like you see them in IE

 And so it shows a folder icon next to each folder in the favorites - again like in IE - just to make list look nicer?

Thanks!

**Comment by gep13** [comment]
@wingers999 thanks for submitting this. I will try to take a look at this, and I will let you know how I get on.

**Comment by gep13** [comment]
@wingers999 I have just commited some additional changes to the source code to include icons similar to what you get within Internet Explorer.  The end result is the following:

![image](https://cloud.githubusercontent.com/assets/1271146/15098112/b389095a-152b-11e6-8f5a-8244229a2373.png)

Let me know if you have any questions.

**Comment by wingers999** [comment]
This seems to just show same icon for all websites? rather than the specific icon for each site??

![gep](https://cloud.githubusercontent.com/assets/10872799/15098144/796b462e-152c-11e6-894b-e38815ee39b9.jpg)

**Comment by gep13** [comment]
>@wingers999 said...
This seems to just show same icon for all websites? rather than the specific icon for each site??

And that is what Internet Explorer does.  At least, that is what the version of Internet Explorer that I have does.  Does yours do something different?

**Comment by wingers999** [comment]
yes mine (and I thought all browsers) show the icon relevant to the website i.e. the websites favicon - as per image below:-

![gep2](https://cloud.githubusercontent.com/assets/10872799/15098842/84765f1a-153e-11e6-8962-60e3a7551c35.png)

**Comment by gep13** [comment]
Hmmm, that is interesting.  I am not seeing that on my system.  @wingers999 can you do me favour...

Can you go to your favourites directory, should be something like `C:\Users\<user name>\Favorites` and copy the contents of the shortcut into this issue?  I am curious if the shortcut itself, which is just an ini file, has been updated with the favicon location, or if it is just loading it as needed from the website.

**Comment by wingers999** [comment]
Yes the path to the favicon is in the shortcut file - see below:-

[{000214A0-0000-0000-C000-000000000046}]
Prop3=19,11
[InternetShortcut]
URL=https://business.santander.co.uk/LGSBBI_NS_ENS/BtoChannelDriver.ssobto?dse_operationName=LGSBBI_LOGON&dse_processorState=initial&redirect=S
IDList=
HotKey=0
IconFile=https://business.santander.co.uk/Estatico/ALP_SBBI_Templates/Images/favicon.ico
IconIndex=1
[Search]
VisitCount=02
SelectionCount=02
DateVisited=2016/04/23:15:13:39.433

**Comment by gep13** [comment]
Ok, perfect, that will help, thanks.

**Comment by gep13** [comment]
@wingers999 okay, have a look at the most recent version.

This is a VERY crude implementation, but it seems to work, and all I have time for just now.  This assumes that you already have the favicon stored within the shortcut ini file.  Internet Explorer must be putting that information in there somehow, but I don't know how/when that happens.  You might want to think about doing that work as well, when browsing the internet with this browser.  i.e. if there isn't a iconfile for a shortcut that you have saved, check to see if there is one, and if there is, update the shortcut.  This would be another pinvoke call, similar to what is being done for reading the ini file currently.

Also, I don't know, off the top of my head, whether the WebClient checks to see if there is a local cached version of an image, before requesting it.  So there might be some optimization that needs to happen in this area.

Hope that helps!

**Comment by PCAssistSoftware** [comment]
Thank you very much indeed - that works perfectly!!!
